swiftmailer:
    transport:        gmail
    username:         mounaamdouni213@gmail.com
    password:         Fati.1999
    host:             smtp
    port:             465
    encryption:       ssl
    auth-mode:        login
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false
